name: Build Windows VST3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v1

      - name: Build Solution
        run: msbuild YourPlugin.sln /p:Configuration=Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VST3-Plugin
          path: path\to\your\build\output\folder
